insert into public.worlds (
    slug,
    title,
    description,
    region_label,
    mascot,
    theme_color,
    accent_color,
    sort_order,
    is_published
)
values
    (
        'selva-algoritmica',
        'Selva Algorítmica',
        'Aprende secuencias, condiciones y bucles guiando al colibrí entre rutas de la selva colombiana.',
        'Amazonía',
        'colibri',
        '#0D1B2A',
        '#F5C518',
        1,
        true
    ),
    (
        'cordillera-binaria',
        'Cordillera Binaria',
        'Resuelve funciones y estructuras de datos mientras asciendes por caminos inspirados en los Andes.',
        'Región Andina',
        'jaguar',
        '#003087',
        '#CE1126',
        2,
        true
    ),
    (
        'costa-de-bugs',
        'Costa de Bugs',
        'Depura código y mejora tu lógica frente a retos rápidos ambientados en el Caribe colombiano.',
        'Caribe',
        'colibri',
        '#CE1126',
        '#F5C518',
        3,
        true
    )
on conflict (slug) do update
set title = excluded.title,
    description = excluded.description,
    region_label = excluded.region_label,
    mascot = excluded.mascot,
    theme_color = excluded.theme_color,
    accent_color = excluded.accent_color,
    sort_order = excluded.sort_order,
    is_published = excluded.is_published;

insert into public.levels (
    world_id,
    slug,
    title,
    description,
    narrative,
    programming_language,
    difficulty,
    xp_reward,
    stars_reward,
    sort_order,
    starter_code,
    validation_rules,
    is_published
)
values
    (
        (select id from public.worlds where slug = 'selva-algoritmica'),
        'ruta-del-colibri',
        'Ruta del Colibrí',
        'Programa una secuencia de pasos para llevar al colibrí hasta la flor correcta.',
        'Tu primera misión consiste en ordenar instrucciones simples sin perder el rumbo.',
        'javascript',
        'beginner',
        100,
        3,
        1,
        'const pasos = []\n\n// Agrega aqui tus instrucciones\n\nreturn pasos',
        '{"goal":"reach_flower","maxSteps":6}'::jsonb,
        true
    ),
    (
        (select id from public.worlds where slug = 'selva-algoritmica'),
        'puente-condicional',
        'Puente Condicional',
        'Usa una condición para elegir el camino seguro del puente.',
        'Las lianas cambian de posición y debes reaccionar según el entorno.',
        'javascript',
        'beginner',
        120,
        3,
        2,
        'const caminoSeguro = (hayTronco) => {\n  // Escribe tu logica aqui\n}\n\nreturn caminoSeguro',
        '{"goal":"choose_safe_path","requiresCondition":true}'::jsonb,
        true
    ),
    (
        (select id from public.worlds where slug = 'selva-algoritmica'),
        'ciclo-del-rio',
        'Ciclo del Río',
        'Repite movimientos usando un bucle para cruzar el río sin desperdiciar pasos.',
        'El río parece largo, pero un patrón correcto te hará avanzar rápido.',
        'javascript',
        'beginner',
        140,
        3,
        3,
        'for (let paso = 0; paso < 0; paso += 1) {\n  // Completa el bucle\n}',
        '{"goal":"repeat_pattern","requiresLoop":true}'::jsonb,
        true
    ),
    (
        (select id from public.worlds where slug = 'cordillera-binaria'),
        'eco-de-funciones',
        'Eco de Funciones',
        'Encapsula movimientos en una función reutilizable para escalar la montaña.',
        'En la altura, repetir código te hace perder tiempo: abstrae y reutiliza.',
        'javascript',
        'intermediate',
        180,
        3,
        1,
        'function avanzarHastaMeta() {\n  // Implementa la funcion\n}\n\nreturn avanzarHastaMeta',
        '{"goal":"reuse_function","requiresFunction":true}'::jsonb,
        true
    ),
    (
        (select id from public.worlds where slug = 'cordillera-binaria'),
        'mochila-de-datos',
        'Mochila de Datos',
        'Organiza suministros usando arreglos y objetos antes de la expedición.',
        'Cada recurso bien guardado evita errores durante la subida.',
        'javascript',
        'intermediate',
        200,
        3,
        2,
        'const mochila = {\n  herramientas: [],\n}\n\nreturn mochila',
        '{"goal":"structure_data","requiresArray":true,"requiresObject":true}'::jsonb,
        true
    ),
    (
        (select id from public.worlds where slug = 'cordillera-binaria'),
        'sendero-recursivo',
        'Sendero Recursivo',
        'Resuelve un camino fractal con una solución recursiva bien controlada.',
        'Cada tramo repite el mismo patrón; la clave está en la condición de corte.',
        'javascript',
        'advanced',
        240,
        3,
        3,
        'function subirEscalon(nivel) {\n  // Implementa la recursion\n}\n\nreturn subirEscalon',
        '{"goal":"solve_recursively","requiresRecursion":true}'::jsonb,
        true
    ),
    (
        (select id from public.worlds where slug = 'costa-de-bugs'),
        'ola-de-errores',
        'Ola de Errores',
        'Encuentra y corrige fallos básicos antes de que la marea suba.',
        'El código parece estable, pero varias líneas esconden errores pequeños.',
        'javascript',
        'beginner',
        150,
        3,
        1,
        'const mensaje = "CodePlay"\nconsole.log(mensaje)',
        '{"goal":"fix_basic_bug","requiresDebugging":true}'::jsonb,
        true
    ),
    (
        (select id from public.worlds where slug = 'costa-de-bugs'),
        'faro-asincrono',
        'Faro Asíncrono',
        'Sincroniza eventos y promesas para encender el faro a tiempo.',
        'Las señales llegan con retraso; debes coordinar el orden correcto.',
        'javascript',
        'intermediate',
        210,
        3,
        2,
        'async function encenderFaro() {\n  // Usa await correctamente\n}\n\nreturn encenderFaro',
        '{"goal":"handle_async_flow","requiresAsyncAwait":true}'::jsonb,
        true
    ),
    (
        (select id from public.worlds where slug = 'costa-de-bugs'),
        'tormenta-final',
        'Tormenta Final',
        'Combina depuración, funciones y estructuras para superar el reto final.',
        'La costa exige todo lo aprendido en una sola misión.',
        'javascript',
        'advanced',
        260,
        3,
        3,
        'function resolverTormenta(estadoInicial) {\n  // Integra tu solucion completa\n}\n\nreturn resolverTormenta',
        '{"goal":"integrated_challenge","requiresDebugging":true,"requiresFunctions":true}'::jsonb,
        true
    )
on conflict (world_id, slug) do update
set title = excluded.title,
    description = excluded.description,
    narrative = excluded.narrative,
    programming_language = excluded.programming_language,
    difficulty = excluded.difficulty,
    xp_reward = excluded.xp_reward,
    stars_reward = excluded.stars_reward,
    sort_order = excluded.sort_order,
    starter_code = excluded.starter_code,
    validation_rules = excluded.validation_rules,
    is_published = excluded.is_published;
