import type { WorldWithStatus } from '../types/world.types';

export const WORLDS_META: WorldWithStatus[] = [
  {
    id: 'world-1',
    name: 'Bosque de Bucles',
    description: 'Aprende a repetir acciones mientras exploras el bosque mágico.',
    orderIndex: 1,
    color: '#855CD6',
    icon: '/assets/images/worlds/forest-icon.svg',
    createdAt: new Date().toISOString(),
    status: 'unlocked',
    progress: 0,
  },
  {
    id: 'world-2',
    name: 'Volcán de Variables',
    description: 'Domina el poder de las variables en este volcán en erupción.',
    orderIndex: 2,
    color: '#FFB840',
    icon: '/assets/images/worlds/volcano-icon.svg',
    createdAt: new Date().toISOString(),
    status: 'locked',
    progress: 0,
  },
  {
    id: 'world-3',
    name: 'Océano de Objetos',
    description: 'Sumérgete en el mundo de los objetos y clases.',
    orderIndex: 3,
    color: '#4ECDC4',
    icon: '/assets/images/worlds/ocean-icon.svg',
    createdAt: new Date().toISOString(),
    status: 'locked',
    progress: 0,
  },
  {
    id: 'world-4',
    name: 'Montaña de Condicionales',
    description: 'Toma decisiones inteligentes en la cima de la montaña.',
    orderIndex: 4,
    color: '#CE1126',
    icon: '/assets/images/worlds/mountain-icon.svg',
    createdAt: new Date().toISOString(),
    status: 'locked',
    progress: 0,
  },
  {
    id: 'world-5',
    name: 'Desierto de Funciones',
    description: 'Crea funciones poderosas para cruzar el desierto.',
    orderIndex: 5,
    color: '#F5C518',
    icon: '/assets/images/worlds/desert-icon.svg',
    createdAt: new Date().toISOString(),
    status: 'locked',
    progress: 0,
  },
];
