export const ROUTES = {
  HOME: '/',
  LANDING: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  SIGNUP_CHILD: '/signup/child',
  SIGNUP_TUTOR: '/signup/tutor',
  DASHBOARD: '/dashboard',
  WORLDS: '/dashboard/worlds',
  TROPHY_ROOM: '/dashboard/trophies',
  CLASSROOM: '/dashboard/classroom',
  SETTINGS: '/dashboard/settings',
  TEACHER: '/teacher',
  TEACHER_GROUPS: '/teacher/groups',
  TEACHER_PANEL: '/teacher/panel',
  TEACHER_SETTINGS: '/teacher/settings',
} as const;
